import SwiftUI
import Cocoa
import Combine

/// 监听系统剪贴板，并通过 SQLite 分页管理历史与收藏。
@MainActor
final class ClipboardManager: ObservableObject {
    @Published private(set) var history: [HistoryItem] = []
    @Published private(set) var favorites: [HistoryItem] = []
    @Published private(set) var historyTotalCount = 0
    @Published private(set) var favoriteTotalCount = 0
    @Published private(set) var isLoadingHistory = true
    @Published private(set) var isLoadingFavorites = true

    var hasMoreHistory: Bool { history.count < historyResultCount }
    var hasMoreFavorites: Bool { favorites.count < favoriteResultCount }

    static let shared = ClipboardManager()

    private let pasteboard = NSPasteboard.general
    private let historyStore = HistoryStore()
    private let pageSize = 100
    private var clipboardChangeCount: Int
    private var clipboardTimer: Timer?
    private var expirationTimer: Timer?

    private var lastText: String?
    private var lastImageDigest: String?
    private var lastFileURLs: [URL]?
    private var latestHistoryItem: HistoryItem?

    private var historyResultCount = 0
    private var favoriteResultCount = 0
    private var historySearchText = ""
    private var favoriteSearchText = ""
    private var historyLoadGeneration = 0
    private var favoriteLoadGeneration = 0
    private var historySearchTask: Task<Void, Never>?
    private var favoriteSearchTask: Task<Void, Never>?
    private var persistenceTask: Task<Void, Never>?
    private var unsavedItems: [UUID: HistoryItem] = [:]

    private let sensitivePasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    private init() {
        clipboardChangeCount = pasteboard.changeCount
        loadInitialPages()
        setupClipboardObserver()
        setupExpirationTimer()
    }

    deinit {
        clipboardTimer?.invalidate()
        expirationTimer?.invalidate()
        historySearchTask?.cancel()
        favoriteSearchTask?.cancel()
    }

    private var expirationCutoff: Date? {
        SettingsManager.shared.storageDuration.days.map {
            Date().addingTimeInterval(-$0)
        }
    }

    private func loadInitialPages() {
        Task { [weak self, historyStore, pageSize] in
            guard let self else { return }
            let result = await historyStore.bootstrap(
                pageSize: pageSize,
                expiredBefore: expirationCutoff
            )

            // 迁移或首次加载期间可能已捕获新的剪贴内容。
            let liveHistory = history
            let liveFavorites = favorites
            let mergedHistory = mergeUnique(liveHistory, result.history.items)
            let mergedFavorites = mergeUnique(liveFavorites, result.favorites.items)
            history = Array(mergedHistory.prefix(max(pageSize, liveHistory.count)))
            favorites = Array(mergedFavorites.prefix(max(pageSize, liveFavorites.count)))
            historyTotalCount = max(result.history.totalCount, mergedHistory.count)
            favoriteTotalCount = max(result.favorites.totalCount, mergedFavorites.count)
            historyResultCount = historyTotalCount
            favoriteResultCount = favoriteTotalCount
            latestHistoryItem = mergedHistory.first
            isLoadingHistory = false
            isLoadingFavorites = false
        }
    }

    private func mergeUnique(_ first: [HistoryItem], _ second: [HistoryItem]) -> [HistoryItem] {
        var seen = Set<UUID>()
        return (first + second)
            .filter { seen.insert($0.id).inserted }
            .sorted { $0.timestamp > $1.timestamp }
    }

    /// 数据库分页结果已经按时间倒序排列，追加时只需去重，避免每翻一页都重排全部数据。
    private func appendUnique(_ newItems: [HistoryItem], to items: inout [HistoryItem]) {
        var existingIDs = Set(items.map(\.id))
        items.append(contentsOf: newItems.filter { existingIDs.insert($0.id).inserted })
    }

    private func setupClipboardObserver() {
        clipboardTimer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.checkClipboard() }
        }
    }

    private func setupExpirationTimer() {
        expirationTimer = Timer.scheduledTimer(withTimeInterval: 3600, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.cleanExpiredItems() }
        }
    }

    private func checkClipboard() {
        guard pasteboard.changeCount != clipboardChangeCount else { return }
        clipboardChangeCount = pasteboard.changeCount

        guard SettingsManager.shared.monitoringEnabled else { return }
        guard !containsSensitiveContent else {
            resetDuplicateTracking()
            return
        }

        let fileOptions: [NSPasteboard.ReadingOptionKey: Any] = [.urlReadingFileURLsOnly: true]
        if let fileURLs = pasteboard.readObjects(forClasses: [NSURL.self], options: fileOptions) as? [URL],
           !fileURLs.isEmpty {
            if fileURLs != lastFileURLs {
                addToHistory(fileURLs: fileURLs)
                lastFileURLs = fileURLs
                lastText = nil
                lastImageDigest = nil
            }
            return
        }

        if let image = pasteboard.readObjects(forClasses: [NSImage.self], options: nil)?.first as? NSImage {
            let item = HistoryItem(image: image)
            guard let imageDigest = item.imageDigest else { return }
            if imageDigest != lastImageDigest {
                addToHistory(item)
                lastImageDigest = imageDigest
                lastText = nil
                lastFileURLs = nil
            }
            return
        }

        if let string = pasteboard.string(forType: .string), string != lastText {
            addToHistory(text: string)
            lastText = string
            lastImageDigest = nil
            lastFileURLs = nil
        }
    }

    private var containsSensitiveContent: Bool {
        let availableTypes = Set(pasteboard.types ?? [])
        return !availableTypes.isDisjoint(with: sensitivePasteboardTypes)
    }

    private func resetDuplicateTracking() {
        lastText = nil
        lastImageDigest = nil
        lastFileURLs = nil
    }

    private func addToHistory(text: String) {
        guard latestHistoryItem?.textContent != text else { return }
        finishAdding(HistoryItem(text: text))
    }

    private func addToHistory(_ item: HistoryItem) {
        guard latestHistoryItem?.imageDigest != item.imageDigest else { return }
        finishAdding(item)
    }

    private func addToHistory(fileURLs: [URL]) {
        let urlStrings = fileURLs.map(\.absoluteString)
        let latestURLs = latestHistoryItem?.resolvedFileURLs.map(\.absoluteString)
        guard latestURLs != urlStrings,
              let item = HistoryItem(fileURLs: fileURLs) else { return }
        finishAdding(item)
    }

    private func finishAdding(_ item: HistoryItem) {
        latestHistoryItem = item
        unsavedItems[item.id] = item
        historyTotalCount += 1
        if matches(item, query: historySearchText) {
            history.insert(item, at: 0)
            historyResultCount += 1
        }
        persist(item)
    }

    private func persist(_ item: HistoryItem) {
        let previousTask = persistenceTask
        let task = Task { [weak self, historyStore] in
            await previousTask?.value
            guard let persistedItem = await historyStore.upsert(item) else { return }
            self?.replaceLoadedItem(with: persistedItem)
        }
        persistenceTask = task
    }

    private func replaceLoadedItem(with item: HistoryItem) {
        unsavedItems.removeValue(forKey: item.id)
        var mergedItem = item
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            // 用户可能在图片落盘完成前已切换收藏状态。
            mergedItem.isFavorite = history[index].isFavorite
            history[index] = mergedItem
        }
        if let index = favorites.firstIndex(where: { $0.id == item.id }) {
            mergedItem.isFavorite = favorites[index].isFavorite
            favorites[index] = mergedItem
        }
        if latestHistoryItem?.id == item.id {
            mergedItem.isFavorite = latestHistoryItem?.isFavorite ?? mergedItem.isFavorite
            latestHistoryItem = mergedItem
        }
    }

    // MARK: - Pagination and search

    func searchHistory(_ searchText: String) {
        historySearchText = searchText
        historyLoadGeneration += 1
        let generation = historyLoadGeneration
        historySearchTask?.cancel()
        isLoadingHistory = true
        let pendingPersistence = persistenceTask
        historySearchTask = Task { [weak self, historyStore, pageSize] in
            try? await Task.sleep(for: .milliseconds(250))
            guard !Task.isCancelled, let self else { return }
            await pendingPersistence?.value
            let page = await historyStore.loadPage(
                .history,
                offset: 0,
                limit: pageSize,
                searchText: searchText
            )
            guard !Task.isCancelled, generation == historyLoadGeneration else { return }
            history = page.items
            historyResultCount = page.totalCount
            isLoadingHistory = false
        }
    }

    func searchFavorites(_ searchText: String) {
        favoriteSearchText = searchText
        favoriteLoadGeneration += 1
        let generation = favoriteLoadGeneration
        favoriteSearchTask?.cancel()
        isLoadingFavorites = true
        let pendingPersistence = persistenceTask
        favoriteSearchTask = Task { [weak self, historyStore, pageSize] in
            try? await Task.sleep(for: .milliseconds(250))
            guard !Task.isCancelled, let self else { return }
            await pendingPersistence?.value
            let page = await historyStore.loadPage(
                .favorites,
                offset: 0,
                limit: pageSize,
                searchText: searchText
            )
            guard !Task.isCancelled, generation == favoriteLoadGeneration else { return }
            favorites = page.items
            favoriteResultCount = page.totalCount
            isLoadingFavorites = false
        }
    }

    func loadMoreHistory() {
        guard hasMoreHistory, !isLoadingHistory else { return }
        isLoadingHistory = true
        let generation = historyLoadGeneration
        let offset = history.count
        let searchText = historySearchText
        let pendingPersistence = persistenceTask
        Task { [weak self, historyStore, pageSize] in
            await pendingPersistence?.value
            let page = await historyStore.loadPage(
                .history,
                offset: offset,
                limit: pageSize,
                searchText: searchText
            )
            guard let self, generation == historyLoadGeneration else { return }
            appendUnique(page.items, to: &history)
            historyResultCount = page.totalCount
            isLoadingHistory = false
        }
    }

    func loadMoreFavorites() {
        guard hasMoreFavorites, !isLoadingFavorites else { return }
        isLoadingFavorites = true
        let generation = favoriteLoadGeneration
        let offset = favorites.count
        let searchText = favoriteSearchText
        let pendingPersistence = persistenceTask
        Task { [weak self, historyStore, pageSize] in
            await pendingPersistence?.value
            let page = await historyStore.loadPage(
                .favorites,
                offset: offset,
                limit: pageSize,
                searchText: searchText
            )
            guard let self, generation == favoriteLoadGeneration else { return }
            appendUnique(page.items, to: &favorites)
            favoriteResultCount = page.totalCount
            isLoadingFavorites = false
        }
    }

    private func matches(_ item: HistoryItem, query: String) -> Bool {
        let normalizedQuery = query.trimmingCharacters(in: .whitespacesAndNewlines)
        return normalizedQuery.isEmpty
            || item.searchableText.localizedCaseInsensitiveContains(normalizedQuery)
    }

    // MARK: - Mutations

    func cleanExpiredItems() {
        guard let expirationCutoff else { return }
        let previousTask = persistenceTask
        let historyQuery = historySearchText
        let favoriteQuery = favoriteSearchText
        let task = Task { [weak self, historyStore, pageSize] in
            await previousTask?.value
            await historyStore.deleteExpired(before: expirationCutoff)
            let counts = await historyStore.counts()
            let historyPage = await historyStore.loadPage(
                .history,
                offset: 0,
                limit: pageSize,
                searchText: historyQuery
            )
            let favoritePage = await historyStore.loadPage(
                .favorites,
                offset: 0,
                limit: pageSize,
                searchText: favoriteQuery
            )
            guard let self else { return }
            history = historyPage.items
            favorites = favoritePage.items
            historyTotalCount = counts.history
            favoriteTotalCount = counts.favorites
            historyResultCount = historyPage.totalCount
            favoriteResultCount = favoritePage.totalCount
            latestHistoryItem = history.first
            isLoadingHistory = false
            isLoadingFavorites = false
        }
        persistenceTask = task
    }

    func toggleFavorite(item: HistoryItem) {
        let currentItem = history.first(where: { $0.id == item.id })
            ?? favorites.first(where: { $0.id == item.id })
            ?? item
        var updatedItem = currentItem
        updatedItem.isFavorite.toggle()

        if let index = history.firstIndex(where: { $0.id == item.id }) {
            history[index] = updatedItem
        }
        if updatedItem.isFavorite {
            favoriteTotalCount += 1
            if matches(updatedItem, query: favoriteSearchText),
               !favorites.contains(where: { $0.id == updatedItem.id }) {
                favorites.insert(updatedItem, at: 0)
                favorites.sort { $0.timestamp > $1.timestamp }
                favoriteResultCount += 1
            }
        } else {
            favoriteTotalCount = max(0, favoriteTotalCount - 1)
            if favorites.contains(where: { $0.id == updatedItem.id }) {
                favoriteResultCount = max(0, favoriteResultCount - 1)
            }
            favorites.removeAll { $0.id == updatedItem.id }
        }
        if latestHistoryItem?.id == updatedItem.id {
            latestHistoryItem = updatedItem
        }
        if unsavedItems[updatedItem.id] != nil {
            unsavedItems[updatedItem.id] = updatedItem
        }

        let previousTask = persistenceTask
        let task = Task { [historyStore] in
            await previousTask?.value
            await historyStore.setFavorite(id: updatedItem.id, isFavorite: updatedItem.isFavorite)
        }
        persistenceTask = task
    }

    func copyToClipboard(item: HistoryItem) {
        PreviewWindowManager.shared.hidePreview()
        pasteboard.clearContents()

        switch item.contentType {
        case .text:
            guard let text = item.textContent else { return }
            pasteboard.setString(text, forType: .string)
            lastText = text
            lastImageDigest = nil
            lastFileURLs = nil
        case .image:
            guard let image = item.image else { return }
            pasteboard.writeObjects([image])
            lastImageDigest = item.imageDigest
            lastText = nil
            lastFileURLs = nil
        case .file:
            let fileURLs = item.resolvedFileURLs
            guard !fileURLs.isEmpty else { return }
            pasteboard.writeObjects(fileURLs.map { $0 as NSURL })
            lastFileURLs = fileURLs
            lastText = nil
            lastImageDigest = nil
        }

        clipboardChangeCount = pasteboard.changeCount
    }

    func removeItem(id: UUID) {
        let item = history.first(where: { $0.id == id })
            ?? favorites.first(where: { $0.id == id })
        guard item != nil else { return }

        history.removeAll { $0.id == id }
        favorites.removeAll { $0.id == id }
        unsavedItems.removeValue(forKey: id)
        historyTotalCount = max(0, historyTotalCount - 1)
        historyResultCount = max(0, historyResultCount - 1)
        if item?.isFavorite == true {
            favoriteTotalCount = max(0, favoriteTotalCount - 1)
            if let item, matches(item, query: favoriteSearchText) {
                favoriteResultCount = max(0, favoriteResultCount - 1)
            }
        }
        if latestHistoryItem?.id == id {
            latestHistoryItem = history.first
        }

        let previousTask = persistenceTask
        let task = Task { [historyStore] in
            await previousTask?.value
            await historyStore.delete(id: id)
        }
        persistenceTask = task
    }

    func clearAll() {
        guard historyTotalCount > 0 || !history.isEmpty || !favorites.isEmpty else { return }
        history.removeAll()
        favorites.removeAll()
        historyTotalCount = 0
        favoriteTotalCount = 0
        historyResultCount = 0
        favoriteResultCount = 0
        latestHistoryItem = nil
        unsavedItems.removeAll()

        let previousTask = persistenceTask
        let task = Task { [historyStore] in
            await previousTask?.value
            await historyStore.deleteAll()
        }
        persistenceTask = task
    }

    /// 应用退出前等待已排队的 SQLite 增量写入完成。
    func flushHistory() async {
        await persistenceTask?.value
        let itemsToRetry = Array(unsavedItems.values)
        for item in itemsToRetry {
            if let persistedItem = await historyStore.upsert(item) {
                replaceLoadedItem(with: persistedItem)
            }
        }
    }
}
